package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class AgentProfitSetting {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.pay_channel_id
	 * @mbggenerated
	 */
	private Integer payChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.trade_type
	 * @mbggenerated
	 */
	private Byte tradeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.percent
	 * @mbggenerated
	 */
	private Integer percent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.floor_number
	 * @mbggenerated
	 */
	private Integer floorNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column agent_profit_settings.agent_id
	 * @mbggenerated
	 */
	private Integer agentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.id
	 * @return  the value of agent_profit_settings.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.id
	 * @param id  the value for agent_profit_settings.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.pay_channel_id
	 * @return  the value of agent_profit_settings.pay_channel_id
	 * @mbggenerated
	 */
	public Integer getPayChannelId() {
		return payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.pay_channel_id
	 * @param payChannelId  the value for agent_profit_settings.pay_channel_id
	 * @mbggenerated
	 */
	public void setPayChannelId(Integer payChannelId) {
		this.payChannelId = payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.trade_type
	 * @return  the value of agent_profit_settings.trade_type
	 * @mbggenerated
	 */
	public Byte getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.trade_type
	 * @param tradeType  the value for agent_profit_settings.trade_type
	 * @mbggenerated
	 */
	public void setTradeType(Byte tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.percent
	 * @return  the value of agent_profit_settings.percent
	 * @mbggenerated
	 */
	public Integer getPercent() {
		return percent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.percent
	 * @param percent  the value for agent_profit_settings.percent
	 * @mbggenerated
	 */
	public void setPercent(Integer percent) {
		this.percent = percent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.floor_number
	 * @return  the value of agent_profit_settings.floor_number
	 * @mbggenerated
	 */
	public Integer getFloorNumber() {
		return floorNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.floor_number
	 * @param floorNumber  the value for agent_profit_settings.floor_number
	 * @mbggenerated
	 */
	public void setFloorNumber(Integer floorNumber) {
		this.floorNumber = floorNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.created_at
	 * @return  the value of agent_profit_settings.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.created_at
	 * @param createdAt  the value for agent_profit_settings.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.updated_at
	 * @return  the value of agent_profit_settings.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.updated_at
	 * @param updatedAt  the value for agent_profit_settings.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column agent_profit_settings.agent_id
	 * @return  the value of agent_profit_settings.agent_id
	 * @mbggenerated
	 */
	public Integer getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column agent_profit_settings.agent_id
	 * @param agentId  the value for agent_profit_settings.agent_id
	 * @mbggenerated
	 */
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}
}