package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CsAgent {
	
	
	
	 /**
     * 申请售后状态（1 待处理, 2 处理中 ,3 已完成,4已取消）
     */
    public static final int STSTUS_1 = 1;
    
    /**
     * 申请售后状态（1 待处理, 2 处理中 ,3 已完成,4已取消）
     */
    public static final int STSTUS_2 = 2;
    
    /**
     * 申请售后状态（1 待处理, 2 处理中 ,3 已完成,4已取消）
     */
    public static final int STSTUS_3 = 3;
    
    /**
     * 申请售后状态（1 待处理, 2 处理中 ,3 已完成,4已取消）
     */
    public static final int STSTUS_4 = 4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.agent_id
	 * @mbggenerated
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.process_user_id
	 * @mbggenerated
	 */
	private Integer processUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.process_user_name
	 * @mbggenerated
	 */
	private String processUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.terminals_quantity
	 * @mbggenerated
	 */
	private Integer terminalsQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.reason
	 * @mbggenerated
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.apply_num
	 * @mbggenerated
	 */
	private String applyNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.cs_agent_marks_id
	 * @mbggenerated
	 */
	private Integer csAgentMarksId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.terminals_list
	 * @mbggenerated
	 */
	private String terminalsList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.id
	 * @return  the value of cs_agents.id
	 * @mbggenerated
	 */
	private String reciver;
	
	private String phone;
	
	
	
	public String getReciver() {
		return reciver;
	}

	public void setReciver(String reciver) {
		this.reciver = reciver;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.id
	 * @param id  the value for cs_agents.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.agent_id
	 * @return  the value of cs_agents.agent_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.agent_id
	 * @param agentId  the value for cs_agents.agent_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.process_user_id
	 * @return  the value of cs_agents.process_user_id
	 * @mbggenerated
	 */
	public Integer getProcessUserId() {
		return processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.process_user_id
	 * @param processUserId  the value for cs_agents.process_user_id
	 * @mbggenerated
	 */
	public void setProcessUserId(Integer processUserId) {
		this.processUserId = processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.process_user_name
	 * @return  the value of cs_agents.process_user_name
	 * @mbggenerated
	 */
	public String getProcessUserName() {
		return processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.process_user_name
	 * @param processUserName  the value for cs_agents.process_user_name
	 * @mbggenerated
	 */
	public void setProcessUserName(String processUserName) {
		this.processUserName = processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.terminals_quantity
	 * @return  the value of cs_agents.terminals_quantity
	 * @mbggenerated
	 */
	public Integer getTerminalsQuantity() {
		return terminalsQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.terminals_quantity
	 * @param terminalsQuantity  the value for cs_agents.terminals_quantity
	 * @mbggenerated
	 */
	public void setTerminalsQuantity(Integer terminalsQuantity) {
		this.terminalsQuantity = terminalsQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.status
	 * @return  the value of cs_agents.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.status
	 * @param status  the value for cs_agents.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.address
	 * @return  the value of cs_agents.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.address
	 * @param address  the value for cs_agents.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.reason
	 * @return  the value of cs_agents.reason
	 * @mbggenerated
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.reason
	 * @param reason  the value for cs_agents.reason
	 * @mbggenerated
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.created_at
	 * @return  the value of cs_agents.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.created_at
	 * @param createdAt  the value for cs_agents.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.updated_at
	 * @return  the value of cs_agents.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.updated_at
	 * @param updatedAt  the value for cs_agents.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.apply_num
	 * @return  the value of cs_agents.apply_num
	 * @mbggenerated
	 */
	public String getApplyNum() {
		return applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.apply_num
	 * @param applyNum  the value for cs_agents.apply_num
	 * @mbggenerated
	 */
	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.cs_agent_marks_id
	 * @return  the value of cs_agents.cs_agent_marks_id
	 * @mbggenerated
	 */
	public Integer getCsAgentMarksId() {
		return csAgentMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.cs_agent_marks_id
	 * @param csAgentMarksId  the value for cs_agents.cs_agent_marks_id
	 * @mbggenerated
	 */
	public void setCsAgentMarksId(Integer csAgentMarksId) {
		this.csAgentMarksId = csAgentMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.terminals_list
	 * @return  the value of cs_agents.terminals_list
	 * @mbggenerated
	 */
	public String getTerminalsList() {
		return terminalsList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.terminals_list
	 * @param terminalsList  the value for cs_agents.terminals_list
	 * @mbggenerated
	 */
	public void setTerminalsList(String terminalsList) {
		this.terminalsList = terminalsList;
	}
}