package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CsAgent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.agent_id
	 * @mbggenerated
	 */
	private Integer agentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.process_user_id
	 * @mbggenerated
	 */
	private Integer processUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.process_user_name
	 * @mbggenerated
	 */
	private String processUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.terminals_quantity
	 * @mbggenerated
	 */
	private Integer terminalsQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.reason
	 * @mbggenerated
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.apply_num
	 * @mbggenerated
	 */
	private String applyNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.cs_agent_marks_id
	 * @mbggenerated
	 */
	private Integer csAgentMarksId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_agents.terminals_list
	 * @mbggenerated
	 */
	private String terminalsList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.id
	 * @return  the value of cs_agents.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.id
	 * @param id  the value for cs_agents.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.agent_id
	 * @return  the value of cs_agents.agent_id
	 * @mbggenerated
	 */
	public Integer getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.agent_id
	 * @param agentId  the value for cs_agents.agent_id
	 * @mbggenerated
	 */
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.process_user_id
	 * @return  the value of cs_agents.process_user_id
	 * @mbggenerated
	 */
	public Integer getProcessUserId() {
		return processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.process_user_id
	 * @param processUserId  the value for cs_agents.process_user_id
	 * @mbggenerated
	 */
	public void setProcessUserId(Integer processUserId) {
		this.processUserId = processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.process_user_name
	 * @return  the value of cs_agents.process_user_name
	 * @mbggenerated
	 */
	public String getProcessUserName() {
		return processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.process_user_name
	 * @param processUserName  the value for cs_agents.process_user_name
	 * @mbggenerated
	 */
	public void setProcessUserName(String processUserName) {
		this.processUserName = processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.terminals_quantity
	 * @return  the value of cs_agents.terminals_quantity
	 * @mbggenerated
	 */
	public Integer getTerminalsQuantity() {
		return terminalsQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.terminals_quantity
	 * @param terminalsQuantity  the value for cs_agents.terminals_quantity
	 * @mbggenerated
	 */
	public void setTerminalsQuantity(Integer terminalsQuantity) {
		this.terminalsQuantity = terminalsQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.status
	 * @return  the value of cs_agents.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.status
	 * @param status  the value for cs_agents.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.address
	 * @return  the value of cs_agents.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.address
	 * @param address  the value for cs_agents.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.reason
	 * @return  the value of cs_agents.reason
	 * @mbggenerated
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.reason
	 * @param reason  the value for cs_agents.reason
	 * @mbggenerated
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.created_at
	 * @return  the value of cs_agents.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.created_at
	 * @param createdAt  the value for cs_agents.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.updated_at
	 * @return  the value of cs_agents.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.updated_at
	 * @param updatedAt  the value for cs_agents.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.apply_num
	 * @return  the value of cs_agents.apply_num
	 * @mbggenerated
	 */
	public String getApplyNum() {
		return applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.apply_num
	 * @param applyNum  the value for cs_agents.apply_num
	 * @mbggenerated
	 */
	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.cs_agent_marks_id
	 * @return  the value of cs_agents.cs_agent_marks_id
	 * @mbggenerated
	 */
	public Integer getCsAgentMarksId() {
		return csAgentMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.cs_agent_marks_id
	 * @param csAgentMarksId  the value for cs_agents.cs_agent_marks_id
	 * @mbggenerated
	 */
	public void setCsAgentMarksId(Integer csAgentMarksId) {
		this.csAgentMarksId = csAgentMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_agents.terminals_list
	 * @return  the value of cs_agents.terminals_list
	 * @mbggenerated
	 */
	public String getTerminalsList() {
		return terminalsList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_agents.terminals_list
	 * @param terminalsList  the value for cs_agents.terminals_list
	 * @mbggenerated
	 */
	public void setTerminalsList(String terminalsList) {
		this.terminalsList = terminalsList;
	}
}