package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CsChange {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.process_user_id
	 * @mbggenerated
	 */
	private Integer processUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.process_user_name
	 * @mbggenerated
	 */
	private String processUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.terminal_id
	 * @mbggenerated
	 */
	private Integer terminalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.receive_address_id
	 * @mbggenerated
	 */
	private Integer receiveAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.reason
	 * @mbggenerated
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.customer_id
	 * @mbggenerated
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.should_cencel
	 * @mbggenerated
	 */
	private Boolean shouldCencel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.cs_cencel_id
	 * @mbggenerated
	 */
	private Integer csCencelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.apply_num
	 * @mbggenerated
	 */
	private String applyNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.cs_changel_marks_id
	 * @mbggenerated
	 */
	private Integer csChangelMarksId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.return_address_id
	 * @mbggenerated
	 */
	private Integer returnAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_changes.templete_info_xml
	 * @mbggenerated
	 */
	private String templeteInfoXml;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.id
	 * @return  the value of cs_changes.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.id
	 * @param id  the value for cs_changes.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.process_user_id
	 * @return  the value of cs_changes.process_user_id
	 * @mbggenerated
	 */
	public Integer getProcessUserId() {
		return processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.process_user_id
	 * @param processUserId  the value for cs_changes.process_user_id
	 * @mbggenerated
	 */
	public void setProcessUserId(Integer processUserId) {
		this.processUserId = processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.process_user_name
	 * @return  the value of cs_changes.process_user_name
	 * @mbggenerated
	 */
	public String getProcessUserName() {
		return processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.process_user_name
	 * @param processUserName  the value for cs_changes.process_user_name
	 * @mbggenerated
	 */
	public void setProcessUserName(String processUserName) {
		this.processUserName = processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.terminal_id
	 * @return  the value of cs_changes.terminal_id
	 * @mbggenerated
	 */
	public Integer getTerminalId() {
		return terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.terminal_id
	 * @param terminalId  the value for cs_changes.terminal_id
	 * @mbggenerated
	 */
	public void setTerminalId(Integer terminalId) {
		this.terminalId = terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.status
	 * @return  the value of cs_changes.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.status
	 * @param status  the value for cs_changes.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.receive_address_id
	 * @return  the value of cs_changes.receive_address_id
	 * @mbggenerated
	 */
	public Integer getReceiveAddressId() {
		return receiveAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.receive_address_id
	 * @param receiveAddressId  the value for cs_changes.receive_address_id
	 * @mbggenerated
	 */
	public void setReceiveAddressId(Integer receiveAddressId) {
		this.receiveAddressId = receiveAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.created_at
	 * @return  the value of cs_changes.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.created_at
	 * @param createdAt  the value for cs_changes.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.updated_at
	 * @return  the value of cs_changes.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.updated_at
	 * @param updatedAt  the value for cs_changes.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.reason
	 * @return  the value of cs_changes.reason
	 * @mbggenerated
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.reason
	 * @param reason  the value for cs_changes.reason
	 * @mbggenerated
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.customer_id
	 * @return  the value of cs_changes.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.customer_id
	 * @param customerId  the value for cs_changes.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.should_cencel
	 * @return  the value of cs_changes.should_cencel
	 * @mbggenerated
	 */
	public Boolean getShouldCencel() {
		return shouldCencel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.should_cencel
	 * @param shouldCencel  the value for cs_changes.should_cencel
	 * @mbggenerated
	 */
	public void setShouldCencel(Boolean shouldCencel) {
		this.shouldCencel = shouldCencel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.cs_cencel_id
	 * @return  the value of cs_changes.cs_cencel_id
	 * @mbggenerated
	 */
	public Integer getCsCencelId() {
		return csCencelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.cs_cencel_id
	 * @param csCencelId  the value for cs_changes.cs_cencel_id
	 * @mbggenerated
	 */
	public void setCsCencelId(Integer csCencelId) {
		this.csCencelId = csCencelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.apply_num
	 * @return  the value of cs_changes.apply_num
	 * @mbggenerated
	 */
	public String getApplyNum() {
		return applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.apply_num
	 * @param applyNum  the value for cs_changes.apply_num
	 * @mbggenerated
	 */
	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.cs_changel_marks_id
	 * @return  the value of cs_changes.cs_changel_marks_id
	 * @mbggenerated
	 */
	public Integer getCsChangelMarksId() {
		return csChangelMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.cs_changel_marks_id
	 * @param csChangelMarksId  the value for cs_changes.cs_changel_marks_id
	 * @mbggenerated
	 */
	public void setCsChangelMarksId(Integer csChangelMarksId) {
		this.csChangelMarksId = csChangelMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.return_address_id
	 * @return  the value of cs_changes.return_address_id
	 * @mbggenerated
	 */
	public Integer getReturnAddressId() {
		return returnAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.return_address_id
	 * @param returnAddressId  the value for cs_changes.return_address_id
	 * @mbggenerated
	 */
	public void setReturnAddressId(Integer returnAddressId) {
		this.returnAddressId = returnAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_changes.templete_info_xml
	 * @return  the value of cs_changes.templete_info_xml
	 * @mbggenerated
	 */
	public String getTempleteInfoXml() {
		return templeteInfoXml;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_changes.templete_info_xml
	 * @param templeteInfoXml  the value for cs_changes.templete_info_xml
	 * @mbggenerated
	 */
	public void setTempleteInfoXml(String templeteInfoXml) {
		this.templeteInfoXml = templeteInfoXml;
	}
}