package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CsOutStorage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.process_user_id
	 * @mbggenerated
	 */
	private Integer processUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.process_user_name
	 * @mbggenerated
	 */
	private String processUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.apply_num
	 * @mbggenerated
	 */
	private String applyNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cs_out_storages.order_types
	 * @mbggenerated
	 */
	private Integer orderTypes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.id
	 * @return  the value of cs_out_storages.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.id
	 * @param id  the value for cs_out_storages.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.process_user_id
	 * @return  the value of cs_out_storages.process_user_id
	 * @mbggenerated
	 */
	public Integer getProcessUserId() {
		return processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.process_user_id
	 * @param processUserId  the value for cs_out_storages.process_user_id
	 * @mbggenerated
	 */
	public void setProcessUserId(Integer processUserId) {
		this.processUserId = processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.process_user_name
	 * @return  the value of cs_out_storages.process_user_name
	 * @mbggenerated
	 */
	public String getProcessUserName() {
		return processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.process_user_name
	 * @param processUserName  the value for cs_out_storages.process_user_name
	 * @mbggenerated
	 */
	public void setProcessUserName(String processUserName) {
		this.processUserName = processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.status
	 * @return  the value of cs_out_storages.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.status
	 * @param status  the value for cs_out_storages.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.order_id
	 * @return  the value of cs_out_storages.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.order_id
	 * @param orderId  the value for cs_out_storages.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.created_at
	 * @return  the value of cs_out_storages.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.created_at
	 * @param createdAt  the value for cs_out_storages.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.updated_at
	 * @return  the value of cs_out_storages.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.updated_at
	 * @param updatedAt  the value for cs_out_storages.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.apply_num
	 * @return  the value of cs_out_storages.apply_num
	 * @mbggenerated
	 */
	public String getApplyNum() {
		return applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.apply_num
	 * @param applyNum  the value for cs_out_storages.apply_num
	 * @mbggenerated
	 */
	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_out_storages.order_types
	 * @return  the value of cs_out_storages.order_types
	 * @mbggenerated
	 */
	public Integer getOrderTypes() {
		return orderTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_out_storages.order_types
	 * @param orderTypes  the value for cs_out_storages.order_types
	 * @mbggenerated
	 */
	public void setOrderTypes(Integer orderTypes) {
		this.orderTypes = orderTypes;
	}
}