package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CsRepair {

	private Integer id;
	private Integer processUserId;
	private String processUserName;
	private Integer terminalId;
	private RepairStatus status;
	private Integer repairPrice;
	private Byte payTypes;
	private Integer receiveAddressId;
	private Integer customerId;
	private Date createdAt;
	private Date updatedAt;
	private String applyNum;
	private Integer csRepairMarksId;
	private Integer returnAddressId;
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.id
	 * @return  the value of cs_repairs.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.id
	 * @param id  the value for cs_repairs.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.process_user_id
	 * @return  the value of cs_repairs.process_user_id
	 * @mbggenerated
	 */
	public Integer getProcessUserId() {
		return processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.process_user_id
	 * @param processUserId  the value for cs_repairs.process_user_id
	 * @mbggenerated
	 */
	public void setProcessUserId(Integer processUserId) {
		this.processUserId = processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.process_user_name
	 * @return  the value of cs_repairs.process_user_name
	 * @mbggenerated
	 */
	public String getProcessUserName() {
		return processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.process_user_name
	 * @param processUserName  the value for cs_repairs.process_user_name
	 * @mbggenerated
	 */
	public void setProcessUserName(String processUserName) {
		this.processUserName = processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.terminal_id
	 * @return  the value of cs_repairs.terminal_id
	 * @mbggenerated
	 */
	public Integer getTerminalId() {
		return terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.terminal_id
	 * @param terminalId  the value for cs_repairs.terminal_id
	 * @mbggenerated
	 */
	public void setTerminalId(Integer terminalId) {
		this.terminalId = terminalId;
	}


    /**  
     * 获取 status  
     * @return status
     */
    public RepairStatus getStatus() {
        return status;
    }

    /**  
     * 设置 status  
     * @param status
     */
    public void setStatus(RepairStatus status) {
        this.status = status;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.repair_price
	 * @return  the value of cs_repairs.repair_price
	 * @mbggenerated
	 */
	public Integer getRepairPrice() {
		return repairPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.repair_price
	 * @param repairPrice  the value for cs_repairs.repair_price
	 * @mbggenerated
	 */
	public void setRepairPrice(Integer repairPrice) {
		this.repairPrice = repairPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.pay_types
	 * @return  the value of cs_repairs.pay_types
	 * @mbggenerated
	 */
	public Byte getPayTypes() {
		return payTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.pay_types
	 * @param payTypes  the value for cs_repairs.pay_types
	 * @mbggenerated
	 */
	public void setPayTypes(Byte payTypes) {
		this.payTypes = payTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.receive_address_id
	 * @return  the value of cs_repairs.receive_address_id
	 * @mbggenerated
	 */
	public Integer getReceiveAddressId() {
		return receiveAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.receive_address_id
	 * @param receiveAddressId  the value for cs_repairs.receive_address_id
	 * @mbggenerated
	 */
	public void setReceiveAddressId(Integer receiveAddressId) {
		this.receiveAddressId = receiveAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.customer_id
	 * @return  the value of cs_repairs.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.customer_id
	 * @param customerId  the value for cs_repairs.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.created_at
	 * @return  the value of cs_repairs.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.created_at
	 * @param createdAt  the value for cs_repairs.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.updated_at
	 * @return  the value of cs_repairs.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.updated_at
	 * @param updatedAt  the value for cs_repairs.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.apply_num
	 * @return  the value of cs_repairs.apply_num
	 * @mbggenerated
	 */
	public String getApplyNum() {
		return applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.apply_num
	 * @param applyNum  the value for cs_repairs.apply_num
	 * @mbggenerated
	 */
	public void setApplyNum(String applyNum) {
		this.applyNum = applyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.cs_repair_marks_id
	 * @return  the value of cs_repairs.cs_repair_marks_id
	 * @mbggenerated
	 */
	public Integer getCsRepairMarksId() {
		return csRepairMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.cs_repair_marks_id
	 * @param csRepairMarksId  the value for cs_repairs.cs_repair_marks_id
	 * @mbggenerated
	 */
	public void setCsRepairMarksId(Integer csRepairMarksId) {
		this.csRepairMarksId = csRepairMarksId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.return_address_id
	 * @return  the value of cs_repairs.return_address_id
	 * @mbggenerated
	 */
	public Integer getReturnAddressId() {
		return returnAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.return_address_id
	 * @param returnAddressId  the value for cs_repairs.return_address_id
	 * @mbggenerated
	 */
	public void setReturnAddressId(Integer returnAddressId) {
		this.returnAddressId = returnAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cs_repairs.description
	 * @return  the value of cs_repairs.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cs_repairs.description
	 * @param description  the value for cs_repairs.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}