package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

/**
 * 积分收支记录表<br>
 * <功能描述>
 *
 * @author Java-007 2015年2月9日
 *
 */
public class CustomerIntegralRecord {

    /**
     * 收入
     */
    public static final int TYPES_1 = 1;

    /**
     * 支出
     */
    public static final int TYPES_2 = 2;

    /**
     * 来源相关类型 - 交易
     */
    public static final int TARGET_TYPE_1 = 1;

    /**
     * 来源相关类型 - 终端购买
     */
    public static final int TARGET_TYPE_2 = 2;

    /**
     * 来源相关类型 - 调整
     */
    public static final int TARGET_TYPE_3 = 3;

    /**
     * 来源相关类型 - 兑换
     */
    public static final int TARGET_TYPE_4 = 4;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_records.id
     * 
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.customer_id
     * 
     * @mbggenerated
     */
    private Integer customerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.types
     * 
     * @mbggenerated
     */
    private Byte types;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.quantity
     * 
     * @mbggenerated
     */
    private Integer quantity;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.target_id
     * 
     * @mbggenerated
     */
    private Integer targetId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.target_type
     * 
     * @mbggenerated
     */
    private Byte targetType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.created_at
     * 
     * @mbggenerated
     */
    private Date createdAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.updated_at
     * 
     * @mbggenerated
     */
    private Date updatedAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_integral_records.description
     * 
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.id
     * 
     * @return the value of customer_integral_records.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.id
     * 
     * @param id
     *            the value for customer_integral_records.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.customer_id
     * 
     * @return the value of customer_integral_records.customer_id
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.customer_id
     * 
     * @param customerId
     *            the value for customer_integral_records.customer_id
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.types
     * 
     * @return the value of customer_integral_records.types
     * @mbggenerated
     */
    public Byte getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.types
     * 
     * @param types
     *            the value for customer_integral_records.types
     * @mbggenerated
     */
    public void setTypes(Byte types) {
        this.types = types;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.quantity
     * 
     * @return the value of customer_integral_records.quantity
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.quantity
     * 
     * @param quantity
     *            the value for customer_integral_records.quantity
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.target_id
     * 
     * @return the value of customer_integral_records.target_id
     * @mbggenerated
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.target_id
     * 
     * @param targetId
     *            the value for customer_integral_records.target_id
     * @mbggenerated
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.target_type
     * 
     * @return the value of customer_integral_records.target_type
     * @mbggenerated
     */
    public Byte getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.target_type
     * 
     * @param targetType
     *            the value for customer_integral_records.target_type
     * @mbggenerated
     */
    public void setTargetType(Byte targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.created_at
     * 
     * @return the value of customer_integral_records.created_at
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.created_at
     * 
     * @param createdAt
     *            the value for customer_integral_records.created_at
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.updated_at
     * 
     * @return the value of customer_integral_records.updated_at
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.updated_at
     * 
     * @param updatedAt
     *            the value for customer_integral_records.updated_at
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_integral_records.description
     * 
     * @return the value of customer_integral_records.description
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_integral_records.description
     * 
     * @param description
     *            the value for customer_integral_records.description
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}