package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CustomerRoleRelation {
	public static final String Right1 = "批购";
	public static final int RoleId1=1;
	
	public static final String Right2 = "代购";
	public static final int RoleId2=2;
	
	public static final String Right3 = "终端管理/售后记录";
	public static final int RoleId3=3;
	
	public static final String Right4 = "交易流水/POS分润";
	public static final int RoleId4=4;
	
	public static final String Right5 = "管理下级代理商";
	public static final int RoleId5=5;
	
	public static final String Right6 = "管理用户";
	public static final int RoleId6=6;
	
	public static final String Right7 = "员工账号";
	public static final int RoleId7=7;
	
	public static final String Right8 = "代理商资料";
	public static final int RoleId8=8;
	
	public static final String Right9 = "库存";
	public static final int RoleId9=9;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column customer_role_relations.id
	 * 
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column customer_role_relations.role_id
	 * 
	 * @mbggenerated
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column customer_role_relations.customer_id
	 * 
	 * @mbggenerated
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column customer_role_relations.created_at
	 * 
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column customer_role_relations.updated_at
	 * 
	 * @mbggenerated
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column customer_role_relations.id
	 * 
	 * @return the value of customer_role_relations.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column customer_role_relations.id
	 * 
	 * @param id
	 *            the value for customer_role_relations.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column customer_role_relations.role_id
	 * 
	 * @return the value of customer_role_relations.role_id
	 * @mbggenerated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column customer_role_relations.role_id
	 * 
	 * @param roleId
	 *            the value for customer_role_relations.role_id
	 * @mbggenerated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column customer_role_relations.customer_id
	 * 
	 * @return the value of customer_role_relations.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column customer_role_relations.customer_id
	 * 
	 * @param customerId
	 *            the value for customer_role_relations.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column customer_role_relations.created_at
	 * 
	 * @return the value of customer_role_relations.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column customer_role_relations.created_at
	 * 
	 * @param createdAt
	 *            the value for customer_role_relations.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column customer_role_relations.updated_at
	 * 
	 * @return the value of customer_role_relations.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column customer_role_relations.updated_at
	 * 
	 * @param updatedAt
	 *            the value for customer_role_relations.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}