package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CustomerIntegralConvert {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.quantity
	 * @mbggenerated
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.bank_name
	 * @mbggenerated
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.bank_account
	 * @mbggenerated
	 */
	private String bankAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.price
	 * @mbggenerated
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.customer_id
	 * @mbggenerated
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.process_user_id
	 * @mbggenerated
	 */
	private Integer processUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer_integral_converts.process_user_name
	 * @mbggenerated
	 */
	private String processUserName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.id
	 * @return  the value of customer_integral_converts.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.id
	 * @param id  the value for customer_integral_converts.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.quantity
	 * @return  the value of customer_integral_converts.quantity
	 * @mbggenerated
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.quantity
	 * @param quantity  the value for customer_integral_converts.quantity
	 * @mbggenerated
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.bank_name
	 * @return  the value of customer_integral_converts.bank_name
	 * @mbggenerated
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.bank_name
	 * @param bankName  the value for customer_integral_converts.bank_name
	 * @mbggenerated
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.bank_account
	 * @return  the value of customer_integral_converts.bank_account
	 * @mbggenerated
	 */
	public String getBankAccount() {
		return bankAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.bank_account
	 * @param bankAccount  the value for customer_integral_converts.bank_account
	 * @mbggenerated
	 */
	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.price
	 * @return  the value of customer_integral_converts.price
	 * @mbggenerated
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.price
	 * @param price  the value for customer_integral_converts.price
	 * @mbggenerated
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.status
	 * @return  the value of customer_integral_converts.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.status
	 * @param status  the value for customer_integral_converts.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.created_at
	 * @return  the value of customer_integral_converts.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.created_at
	 * @param createdAt  the value for customer_integral_converts.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.updated_at
	 * @return  the value of customer_integral_converts.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.updated_at
	 * @param updatedAt  the value for customer_integral_converts.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.customer_id
	 * @return  the value of customer_integral_converts.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.customer_id
	 * @param customerId  the value for customer_integral_converts.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.process_user_id
	 * @return  the value of customer_integral_converts.process_user_id
	 * @mbggenerated
	 */
	public Integer getProcessUserId() {
		return processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.process_user_id
	 * @param processUserId  the value for customer_integral_converts.process_user_id
	 * @mbggenerated
	 */
	public void setProcessUserId(Integer processUserId) {
		this.processUserId = processUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer_integral_converts.process_user_name
	 * @return  the value of customer_integral_converts.process_user_name
	 * @mbggenerated
	 */
	public String getProcessUserName() {
		return processUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer_integral_converts.process_user_name
	 * @param processUserName  the value for customer_integral_converts.process_user_name
	 * @mbggenerated
	 */
	public void setProcessUserName(String processUserName) {
		this.processUserName = processUserName;
	}
}