package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class CustomerAddress {

    /**
     * 是否默认地址（是）
     */
    public static final int ISDEFAULT_1 = 1;

    /**
     * 是否默认地址（否）
     * 
     */
    public static final int ISDEFAULT_2 = 2;
    
    /**
     * 有效
     * 
     */
    public static final int STATUS_1 = 1;
    /**
     * 删除
     * 
     */
    public static final int STATUS_2 = 2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_addresses.id
     * 
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_addresses.city_id
     * 
     * @mbggenerated
     */
    private Integer cityId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_addresses.receiver
     * 
     * @mbggenerated
     */
    private String receiver;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_addresses.address
     * 
     * @mbggenerated
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_addresses.moblephone
     * 
     * @mbggenerated
     */
    private String moblephone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_addresses.zip_code
     * 
     * @mbggenerated
     */
    private String zipCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_addresses.is_default
     * 
     * @mbggenerated
     */
    private Integer isDefault;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_addresses.customer_id
     * 
     * @mbggenerated
     */
    private Integer customerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_addresses.status
     * 
     * @mbggenerated
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_addresses.created_at
     * 
     * @mbggenerated
     */
    private Date createdAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * customer_addresses.updated_at
     * 
     * @mbggenerated
     */
    private Date updatedAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_addresses.telphone
     * 
     * @mbggenerated
     */
    private String telphone;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.id
     * 
     * @return the value of customer_addresses.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_addresses.id
     * 
     * @param id
     *            the value for customer_addresses.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.city_id
     * 
     * @return the value of customer_addresses.city_id
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.city_id
     * 
     * @param cityId
     *            the value for customer_addresses.city_id
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.receiver
     * 
     * @return the value of customer_addresses.receiver
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.receiver
     * 
     * @param receiver
     *            the value for customer_addresses.receiver
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.address
     * 
     * @return the value of customer_addresses.address
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.address
     * 
     * @param address
     *            the value for customer_addresses.address
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.moblephone
     * 
     * @return the value of customer_addresses.moblephone
     * @mbggenerated
     */
    public String getMoblephone() {
        return moblephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.moblephone
     * 
     * @param moblephone
     *            the value for customer_addresses.moblephone
     * @mbggenerated
     */
    public void setMoblephone(String moblephone) {
        this.moblephone = moblephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.zip_code
     * 
     * @return the value of customer_addresses.zip_code
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.zip_code
     * 
     * @param zipCode
     *            the value for customer_addresses.zip_code
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.is_default
     * 
     * @return the value of customer_addresses.is_default
     * @mbggenerated
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.is_default
     * 
     * @param isDefault
     *            the value for customer_addresses.is_default
     * @mbggenerated
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.customer_id
     * 
     * @return the value of customer_addresses.customer_id
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.customer_id
     * 
     * @param customerId
     *            the value for customer_addresses.customer_id
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.status
     * 
     * @return the value of customer_addresses.status
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.status
     * 
     * @param status
     *            the value for customer_addresses.status
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.created_at
     * 
     * @return the value of customer_addresses.created_at
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.created_at
     * 
     * @param createdAt
     *            the value for customer_addresses.created_at
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.updated_at
     * 
     * @return the value of customer_addresses.updated_at
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.updated_at
     * 
     * @param updatedAt
     *            the value for customer_addresses.updated_at
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * customer_addresses.telphone
     * 
     * @return the value of customer_addresses.telphone
     * @mbggenerated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * customer_addresses.telphone
     * 
     * @param telphone
     *            the value for customer_addresses.telphone
     * @mbggenerated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }
}