package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class DangerMerchant {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column danger_merchants.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column danger_merchants.credit_type_id
	 * @mbggenerated
	 */
	private Integer creditTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column danger_merchants.card_id
	 * @mbggenerated
	 */
	private Integer cardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column danger_merchants.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column danger_merchants.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column danger_merchants.id
	 * @return  the value of danger_merchants.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column danger_merchants.id
	 * @param id  the value for danger_merchants.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column danger_merchants.credit_type_id
	 * @return  the value of danger_merchants.credit_type_id
	 * @mbggenerated
	 */
	public Integer getCreditTypeId() {
		return creditTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column danger_merchants.credit_type_id
	 * @param creditTypeId  the value for danger_merchants.credit_type_id
	 * @mbggenerated
	 */
	public void setCreditTypeId(Integer creditTypeId) {
		this.creditTypeId = creditTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column danger_merchants.card_id
	 * @return  the value of danger_merchants.card_id
	 * @mbggenerated
	 */
	public Integer getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column danger_merchants.card_id
	 * @param cardId  the value for danger_merchants.card_id
	 * @mbggenerated
	 */
	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column danger_merchants.created_at
	 * @return  the value of danger_merchants.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column danger_merchants.created_at
	 * @param createdAt  the value for danger_merchants.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column danger_merchants.updated_at
	 * @return  the value of danger_merchants.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column danger_merchants.updated_at
	 * @param updatedAt  the value for danger_merchants.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}