package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class DictionaryOpenPrivateInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dictionary_open_private_infos.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dictionary_open_private_infos.info_type
	 * @mbggenerated
	 */
	private Byte infoType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dictionary_open_private_infos.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dictionary_open_private_infos.query_mark
	 * @mbggenerated
	 */
	private String queryMark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dictionary_open_private_infos.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dictionary_open_private_infos.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dictionary_open_private_infos.introduction
	 * @mbggenerated
	 */
	private String introduction;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dictionary_open_private_infos.id
	 * @return  the value of dictionary_open_private_infos.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dictionary_open_private_infos.id
	 * @param id  the value for dictionary_open_private_infos.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dictionary_open_private_infos.info_type
	 * @return  the value of dictionary_open_private_infos.info_type
	 * @mbggenerated
	 */
	public Byte getInfoType() {
		return infoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dictionary_open_private_infos.info_type
	 * @param infoType  the value for dictionary_open_private_infos.info_type
	 * @mbggenerated
	 */
	public void setInfoType(Byte infoType) {
		this.infoType = infoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dictionary_open_private_infos.name
	 * @return  the value of dictionary_open_private_infos.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dictionary_open_private_infos.name
	 * @param name  the value for dictionary_open_private_infos.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dictionary_open_private_infos.query_mark
	 * @return  the value of dictionary_open_private_infos.query_mark
	 * @mbggenerated
	 */
	public String getQueryMark() {
		return queryMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dictionary_open_private_infos.query_mark
	 * @param queryMark  the value for dictionary_open_private_infos.query_mark
	 * @mbggenerated
	 */
	public void setQueryMark(String queryMark) {
		this.queryMark = queryMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dictionary_open_private_infos.created_at
	 * @return  the value of dictionary_open_private_infos.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dictionary_open_private_infos.created_at
	 * @param createdAt  the value for dictionary_open_private_infos.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dictionary_open_private_infos.updated_at
	 * @return  the value of dictionary_open_private_infos.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dictionary_open_private_infos.updated_at
	 * @param updatedAt  the value for dictionary_open_private_infos.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dictionary_open_private_infos.introduction
	 * @return  the value of dictionary_open_private_infos.introduction
	 * @mbggenerated
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dictionary_open_private_infos.introduction
	 * @param introduction  the value for dictionary_open_private_infos.introduction
	 * @mbggenerated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}
}