package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class GoodComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.score
	 * @mbggenerated
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.customer_id
	 * @mbggenerated
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.verify_user_id
	 * @mbggenerated
	 */
	private Integer verifyUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.verify_type
	 * @mbggenerated
	 */
	private Boolean verifyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.verified_at
	 * @mbggenerated
	 */
	private Date verifiedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.good_id
	 * @mbggenerated
	 */
	private Integer goodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_comments.content
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.id
	 * @return  the value of good_comments.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.id
	 * @param id  the value for good_comments.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.score
	 * @return  the value of good_comments.score
	 * @mbggenerated
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.score
	 * @param score  the value for good_comments.score
	 * @mbggenerated
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.customer_id
	 * @return  the value of good_comments.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.customer_id
	 * @param customerId  the value for good_comments.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.verify_user_id
	 * @return  the value of good_comments.verify_user_id
	 * @mbggenerated
	 */
	public Integer getVerifyUserId() {
		return verifyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.verify_user_id
	 * @param verifyUserId  the value for good_comments.verify_user_id
	 * @mbggenerated
	 */
	public void setVerifyUserId(Integer verifyUserId) {
		this.verifyUserId = verifyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.verify_type
	 * @return  the value of good_comments.verify_type
	 * @mbggenerated
	 */
	public Boolean getVerifyType() {
		return verifyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.verify_type
	 * @param verifyType  the value for good_comments.verify_type
	 * @mbggenerated
	 */
	public void setVerifyType(Boolean verifyType) {
		this.verifyType = verifyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.verified_at
	 * @return  the value of good_comments.verified_at
	 * @mbggenerated
	 */
	public Date getVerifiedAt() {
		return verifiedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.verified_at
	 * @param verifiedAt  the value for good_comments.verified_at
	 * @mbggenerated
	 */
	public void setVerifiedAt(Date verifiedAt) {
		this.verifiedAt = verifiedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.order_id
	 * @return  the value of good_comments.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.order_id
	 * @param orderId  the value for good_comments.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.status
	 * @return  the value of good_comments.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.status
	 * @param status  the value for good_comments.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.good_id
	 * @return  the value of good_comments.good_id
	 * @mbggenerated
	 */
	public Integer getGoodId() {
		return goodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.good_id
	 * @param goodId  the value for good_comments.good_id
	 * @mbggenerated
	 */
	public void setGoodId(Integer goodId) {
		this.goodId = goodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.created_at
	 * @return  the value of good_comments.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.created_at
	 * @param createdAt  the value for good_comments.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.updated_at
	 * @return  the value of good_comments.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.updated_at
	 * @param updatedAt  the value for good_comments.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_comments.content
	 * @return  the value of good_comments.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_comments.content
	 * @param content  the value for good_comments.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content;
	}
}