package com.comdosoft.financial.user.domain.zhangfu;

public class MessageReceiver {

	private Integer id;
	private Integer customerId;
	private SysMessage sysMessage;
	private Integer status;

	
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_receivers.id
	 * @param id  the value for message_receivers.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_receivers.customer_id
	 * @return  the value of message_receivers.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_receivers.customer_id
	 * @param customerId  the value for message_receivers.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_receivers.sys_message_id
	 * @return  the value of message_receivers.sys_message_id
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_receivers.sys_message_id
	 * @param sysMessageId  the value for message_receivers.sys_message_id
	 * @mbggenerated
	 */

 
	 
    public SysMessage getSysMessage() {
        return sysMessage;
    }

   
    /**  
     * 获取 status  
     * @return status
     */
    public Integer getStatus() {
        return status;
    }

    /**  
     * 设置 status  
     * @param status
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public void setSysMessage(SysMessage sysMessage) {
        this.sysMessage = sysMessage;
    }
 
}