package com.comdosoft.financial.user.domain.zhangfu;

public class OpeningRequirement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.level_title
	 * @mbggenerated
	 */
	private String levelTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.level_description
	 * @mbggenerated
	 */
	private String levelDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.pay_channel_id
	 * @mbggenerated
	 */
	private Integer payChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.has_video_verify
	 * @mbggenerated
	 */
	private Boolean hasVideoVerify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.level
	 * @mbggenerated
	 */
	private Byte level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.video_verify_status
	 * @mbggenerated
	 */
	private Integer videoVerifyStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_requirements.opening_requirement_id
	 * @mbggenerated
	 */
	private Integer openingRequirementId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.id
	 * @return  the value of opening_requirements.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.id
	 * @param id  the value for opening_requirements.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.level_title
	 * @return  the value of opening_requirements.level_title
	 * @mbggenerated
	 */
	public String getLevelTitle() {
		return levelTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.level_title
	 * @param levelTitle  the value for opening_requirements.level_title
	 * @mbggenerated
	 */
	public void setLevelTitle(String levelTitle) {
		this.levelTitle = levelTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.level_description
	 * @return  the value of opening_requirements.level_description
	 * @mbggenerated
	 */
	public String getLevelDescription() {
		return levelDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.level_description
	 * @param levelDescription  the value for opening_requirements.level_description
	 * @mbggenerated
	 */
	public void setLevelDescription(String levelDescription) {
		this.levelDescription = levelDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.pay_channel_id
	 * @return  the value of opening_requirements.pay_channel_id
	 * @mbggenerated
	 */
	public Integer getPayChannelId() {
		return payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.pay_channel_id
	 * @param payChannelId  the value for opening_requirements.pay_channel_id
	 * @mbggenerated
	 */
	public void setPayChannelId(Integer payChannelId) {
		this.payChannelId = payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.has_video_verify
	 * @return  the value of opening_requirements.has_video_verify
	 * @mbggenerated
	 */
	public Boolean getHasVideoVerify() {
		return hasVideoVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.has_video_verify
	 * @param hasVideoVerify  the value for opening_requirements.has_video_verify
	 * @mbggenerated
	 */
	public void setHasVideoVerify(Boolean hasVideoVerify) {
		this.hasVideoVerify = hasVideoVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.level
	 * @return  the value of opening_requirements.level
	 * @mbggenerated
	 */
	public Byte getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.level
	 * @param level  the value for opening_requirements.level
	 * @mbggenerated
	 */
	public void setLevel(Byte level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.video_verify_status
	 * @return  the value of opening_requirements.video_verify_status
	 * @mbggenerated
	 */
	public Integer getVideoVerifyStatus() {
		return videoVerifyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.video_verify_status
	 * @param videoVerifyStatus  the value for opening_requirements.video_verify_status
	 * @mbggenerated
	 */
	public void setVideoVerifyStatus(Integer videoVerifyStatus) {
		this.videoVerifyStatus = videoVerifyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_requirements.opening_requirement_id
	 * @return  the value of opening_requirements.opening_requirement_id
	 * @mbggenerated
	 */
	public Integer getOpeningRequirementId() {
		return openingRequirementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_requirements.opening_requirement_id
	 * @param openingRequirementId  the value for opening_requirements.opening_requirement_id
	 * @mbggenerated
	 */
	public void setOpeningRequirementId(Integer openingRequirementId) {
		this.openingRequirementId = openingRequirementId;
	}
	
	/**
	 * 是否需要视频认证1.需要
	 */
	public final static int TYPE_1 = 1;
	
	/**
	 * 是否需要视频认证0.不需要
	 */
	public final static int TYPE_2 = 0;
}