package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class OpeningApplie {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.apply_customer_id
	 * @mbggenerated
	 */
	private Integer applyCustomerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.preliminary_verify_user_id
	 * @mbggenerated
	 */
	private Integer preliminaryVerifyUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.terminal_id
	 * @mbggenerated
	 */
	private Integer terminalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.opening_apply_mark_id
	 * @mbggenerated
	 */
	private Integer openingApplyMarkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_applies.types
	 * @mbggenerated
	 */
	private Integer types;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.id
	 * @return  the value of opening_applies.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.id
	 * @param id  the value for opening_applies.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.apply_customer_id
	 * @return  the value of opening_applies.apply_customer_id
	 * @mbggenerated
	 */
	public Integer getApplyCustomerId() {
		return applyCustomerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.apply_customer_id
	 * @param applyCustomerId  the value for opening_applies.apply_customer_id
	 * @mbggenerated
	 */
	public void setApplyCustomerId(Integer applyCustomerId) {
		this.applyCustomerId = applyCustomerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.preliminary_verify_user_id
	 * @return  the value of opening_applies.preliminary_verify_user_id
	 * @mbggenerated
	 */
	public Integer getPreliminaryVerifyUserId() {
		return preliminaryVerifyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.preliminary_verify_user_id
	 * @param preliminaryVerifyUserId  the value for opening_applies.preliminary_verify_user_id
	 * @mbggenerated
	 */
	public void setPreliminaryVerifyUserId(Integer preliminaryVerifyUserId) {
		this.preliminaryVerifyUserId = preliminaryVerifyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.terminal_id
	 * @return  the value of opening_applies.terminal_id
	 * @mbggenerated
	 */
	public Integer getTerminalId() {
		return terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.terminal_id
	 * @param terminalId  the value for opening_applies.terminal_id
	 * @mbggenerated
	 */
	public void setTerminalId(Integer terminalId) {
		this.terminalId = terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.status
	 * @return  the value of opening_applies.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.status
	 * @param status  the value for opening_applies.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.created_at
	 * @return  the value of opening_applies.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.created_at
	 * @param createdAt  the value for opening_applies.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.updated_at
	 * @return  the value of opening_applies.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.updated_at
	 * @param updatedAt  the value for opening_applies.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.opening_apply_mark_id
	 * @return  the value of opening_applies.opening_apply_mark_id
	 * @mbggenerated
	 */
	public Integer getOpeningApplyMarkId() {
		return openingApplyMarkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.opening_apply_mark_id
	 * @param openingApplyMarkId  the value for opening_applies.opening_apply_mark_id
	 * @mbggenerated
	 */
	public void setOpeningApplyMarkId(Integer openingApplyMarkId) {
		this.openingApplyMarkId = openingApplyMarkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_applies.types
	 * @return  the value of opening_applies.types
	 * @mbggenerated
	 */
	public Integer getTypes() {
		return types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_applies.types
	 * @param types  the value for opening_applies.types
	 * @mbggenerated
	 */
	public void setTypes(Integer types) {
		this.types = types;
	}
}