package com.comdosoft.financial.user.domain.zhangfu;

public class OrderReceiverAddress {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receiver_addresses.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receiver_addresses.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receiver_addresses.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receiver_addresses.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receiver_addresses.zip_code
	 * @mbggenerated
	 */
	private String zipCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receiver_addresses.customer_id
	 * @mbggenerated
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_receiver_addresses.customer_address_id
	 * @mbggenerated
	 */
	private Integer customerAddressId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receiver_addresses.id
	 * @return  the value of order_receiver_addresses.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receiver_addresses.id
	 * @param id  the value for order_receiver_addresses.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receiver_addresses.order_id
	 * @return  the value of order_receiver_addresses.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receiver_addresses.order_id
	 * @param orderId  the value for order_receiver_addresses.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receiver_addresses.address
	 * @return  the value of order_receiver_addresses.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receiver_addresses.address
	 * @param address  the value for order_receiver_addresses.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receiver_addresses.phone
	 * @return  the value of order_receiver_addresses.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receiver_addresses.phone
	 * @param phone  the value for order_receiver_addresses.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receiver_addresses.zip_code
	 * @return  the value of order_receiver_addresses.zip_code
	 * @mbggenerated
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receiver_addresses.zip_code
	 * @param zipCode  the value for order_receiver_addresses.zip_code
	 * @mbggenerated
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receiver_addresses.customer_id
	 * @return  the value of order_receiver_addresses.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receiver_addresses.customer_id
	 * @param customerId  the value for order_receiver_addresses.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_receiver_addresses.customer_address_id
	 * @return  the value of order_receiver_addresses.customer_address_id
	 * @mbggenerated
	 */
	public Integer getCustomerAddressId() {
		return customerAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_receiver_addresses.customer_address_id
	 * @param customerAddressId  the value for order_receiver_addresses.customer_address_id
	 * @mbggenerated
	 */
	public void setCustomerAddressId(Integer customerAddressId) {
		this.customerAddressId = customerAddressId;
	}
}