package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class OrderGood {

	private Integer id;
	private Good good;
	private PayChannel payChannel;
	private Integer quantity;
	private Integer price;
	private Integer actualPrice;
	private Date createdAt;
	private Date updatedAt;
	private Order order;
	

	/**  
     * 获取 payChannel  
     * @return payChannel
     */
    public PayChannel getPayChannel() {
        return payChannel;
    }

    /**  
     * 设置 payChannel  
     * @param payChannel
     */
    public void setPayChannel(PayChannel payChannel) {
        this.payChannel = payChannel;
    }

    /**  
     * 获取 order  
     * @return order
     */
    public Order getOrder() {
        return order;
    }

    /**  
     * 设置 order  
     * @param order
     */
    public void setOrder(Order order) {
        this.order = order;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.id
	 * @return  the value of order_goods.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.id
	 * @param id  the value for order_goods.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

    /**  
     * 获取 good  
     * @return good
     */
    public Good getGood() {
        return good;
    }

    /**  
     * 设置 good  
     * @param good
     */
    public void setGood(Good good) {
        this.good = good;
    }

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.quantity
	 * @return  the value of order_goods.quantity
	 * @mbggenerated
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.quantity
	 * @param quantity  the value for order_goods.quantity
	 * @mbggenerated
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.price
	 * @return  the value of order_goods.price
	 * @mbggenerated
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.price
	 * @param price  the value for order_goods.price
	 * @mbggenerated
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.actual_price
	 * @return  the value of order_goods.actual_price
	 * @mbggenerated
	 */
	public Integer getActualPrice() {
		return actualPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.actual_price
	 * @param actualPrice  the value for order_goods.actual_price
	 * @mbggenerated
	 */
	public void setActualPrice(Integer actualPrice) {
		this.actualPrice = actualPrice;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.created_at
	 * @return  the value of order_goods.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.created_at
	 * @param createdAt  the value for order_goods.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.updated_at
	 * @return  the value of order_goods.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.updated_at
	 * @param updatedAt  the value for order_goods.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}