package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class OrderMark {

	private Integer id;
	private Integer orderId;
	private Customer customer;
	private Date createdAt;
	private String content;
	
	/**  
     * 获取 customer  
     * @return customer
     */
    public Customer getCustomer() {
        return customer;
    }

    /**  
     * 设置 customer  
     * @param customer
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_marks.id
	 * @return  the value of order_marks.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_marks.id
	 * @param id  the value for order_marks.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_marks.order_id
	 * @return  the value of order_marks.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_marks.order_id
	 * @param orderId  the value for order_marks.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_marks.created_at
	 * @return  the value of order_marks.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_marks.created_at
	 * @param createdAt  the value for order_marks.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_marks.content
	 * @return  the value of order_marks.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_marks.content
	 * @param content  the value for order_marks.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content;
	}
}