package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class OrderLogistic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_logistics.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_logistics.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_logistics.logistics_name
	 * @mbggenerated
	 */
	private String logisticsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_logistics.logistics_number
	 * @mbggenerated
	 */
	private String logisticsNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_logistics.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_logistics.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_logistics.cs_out_storage_id
	 * @mbggenerated
	 */
	private Integer csOutStorageId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_logistics.id
	 * @return  the value of order_logistics.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_logistics.id
	 * @param id  the value for order_logistics.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_logistics.order_id
	 * @return  the value of order_logistics.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_logistics.order_id
	 * @param orderId  the value for order_logistics.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_logistics.logistics_name
	 * @return  the value of order_logistics.logistics_name
	 * @mbggenerated
	 */
	public String getLogisticsName() {
		return logisticsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_logistics.logistics_name
	 * @param logisticsName  the value for order_logistics.logistics_name
	 * @mbggenerated
	 */
	public void setLogisticsName(String logisticsName) {
		this.logisticsName = logisticsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_logistics.logistics_number
	 * @return  the value of order_logistics.logistics_number
	 * @mbggenerated
	 */
	public String getLogisticsNumber() {
		return logisticsNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_logistics.logistics_number
	 * @param logisticsNumber  the value for order_logistics.logistics_number
	 * @mbggenerated
	 */
	public void setLogisticsNumber(String logisticsNumber) {
		this.logisticsNumber = logisticsNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_logistics.created_at
	 * @return  the value of order_logistics.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_logistics.created_at
	 * @param createdAt  the value for order_logistics.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_logistics.updated_at
	 * @return  the value of order_logistics.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_logistics.updated_at
	 * @param updatedAt  the value for order_logistics.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_logistics.cs_out_storage_id
	 * @return  the value of order_logistics.cs_out_storage_id
	 * @mbggenerated
	 */
	public Integer getCsOutStorageId() {
		return csOutStorageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_logistics.cs_out_storage_id
	 * @param csOutStorageId  the value for order_logistics.cs_out_storage_id
	 * @mbggenerated
	 */
	public void setCsOutStorageId(Integer csOutStorageId) {
		this.csOutStorageId = csOutStorageId;
	}
}