package com.comdosoft.financial.user.domain.zhangfu;

public class PayChannelBillingCycle {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.pay_channel_id
	 * @mbggenerated
	 */
	private Integer payChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.billing_cycles_id
	 * @mbggenerated
	 */
	private Integer billingCyclesId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.id
	 * @return  the value of pay_channel_billing_cycles.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.id
	 * @param id  the value for pay_channel_billing_cycles.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.pay_channel_id
	 * @return  the value of pay_channel_billing_cycles.pay_channel_id
	 * @mbggenerated
	 */
	public Integer getPayChannelId() {
		return payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.pay_channel_id
	 * @param payChannelId  the value for pay_channel_billing_cycles.pay_channel_id
	 * @mbggenerated
	 */
	public void setPayChannelId(Integer payChannelId) {
		this.payChannelId = payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.billing_cycles_id
	 * @return  the value of pay_channel_billing_cycles.billing_cycles_id
	 * @mbggenerated
	 */
	public Integer getBillingCyclesId() {
		return billingCyclesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.billing_cycles_id
	 * @param billingCyclesId  the value for pay_channel_billing_cycles.billing_cycles_id
	 * @mbggenerated
	 */
	public void setBillingCyclesId(Integer billingCyclesId) {
		this.billingCyclesId = billingCyclesId;
	}
}