package com.comdosoft.financial.user.domain.zhangfu;

public class SupportTradeType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.trade_type
	 * @mbggenerated
	 */
	private Integer tradeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.base_profit
	 * @mbggenerated
	 */
	private Integer baseProfit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.terminal_rate
	 * @mbggenerated
	 */
	private Integer terminalRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.base_rate
	 * @mbggenerated
	 */
	private Integer baseRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.floor_profit
	 * @mbggenerated
	 */
	private Integer floorProfit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.top_profit
	 * @mbggenerated
	 */
	private Integer topProfit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.sort_index
	 * @mbggenerated
	 */
	private Integer sortIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.pay_channel_id
	 * @mbggenerated
	 */
	private Integer payChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.factory_id
	 * @mbggenerated
	 */
	private Integer factoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.service_rate
	 * @mbggenerated
	 */
	private Integer serviceRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.service_profit
	 * @mbggenerated
	 */
	private Integer serviceProfit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.trade_type_id
	 * @mbggenerated
	 */
	private Integer tradeTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.top_charge
	 * @mbggenerated
	 */
	private Integer topCharge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.floor_charge
	 * @mbggenerated
	 */
	private Integer floorCharge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column support_trade_types.description
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.id
	 * @return  the value of support_trade_types.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.id
	 * @param id  the value for support_trade_types.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.trade_type
	 * @return  the value of support_trade_types.trade_type
	 * @mbggenerated
	 */
	public Integer getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.trade_type
	 * @param tradeType  the value for support_trade_types.trade_type
	 * @mbggenerated
	 */
	public void setTradeType(Integer tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.base_profit
	 * @return  the value of support_trade_types.base_profit
	 * @mbggenerated
	 */
	public Integer getBaseProfit() {
		return baseProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.base_profit
	 * @param baseProfit  the value for support_trade_types.base_profit
	 * @mbggenerated
	 */
	public void setBaseProfit(Integer baseProfit) {
		this.baseProfit = baseProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.terminal_rate
	 * @return  the value of support_trade_types.terminal_rate
	 * @mbggenerated
	 */
	public Integer getTerminalRate() {
		return terminalRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.terminal_rate
	 * @param terminalRate  the value for support_trade_types.terminal_rate
	 * @mbggenerated
	 */
	public void setTerminalRate(Integer terminalRate) {
		this.terminalRate = terminalRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.base_rate
	 * @return  the value of support_trade_types.base_rate
	 * @mbggenerated
	 */
	public Integer getBaseRate() {
		return baseRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.base_rate
	 * @param baseRate  the value for support_trade_types.base_rate
	 * @mbggenerated
	 */
	public void setBaseRate(Integer baseRate) {
		this.baseRate = baseRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.floor_profit
	 * @return  the value of support_trade_types.floor_profit
	 * @mbggenerated
	 */
	public Integer getFloorProfit() {
		return floorProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.floor_profit
	 * @param floorProfit  the value for support_trade_types.floor_profit
	 * @mbggenerated
	 */
	public void setFloorProfit(Integer floorProfit) {
		this.floorProfit = floorProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.top_profit
	 * @return  the value of support_trade_types.top_profit
	 * @mbggenerated
	 */
	public Integer getTopProfit() {
		return topProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.top_profit
	 * @param topProfit  the value for support_trade_types.top_profit
	 * @mbggenerated
	 */
	public void setTopProfit(Integer topProfit) {
		this.topProfit = topProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.sort_index
	 * @return  the value of support_trade_types.sort_index
	 * @mbggenerated
	 */
	public Integer getSortIndex() {
		return sortIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.sort_index
	 * @param sortIndex  the value for support_trade_types.sort_index
	 * @mbggenerated
	 */
	public void setSortIndex(Integer sortIndex) {
		this.sortIndex = sortIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.pay_channel_id
	 * @return  the value of support_trade_types.pay_channel_id
	 * @mbggenerated
	 */
	public Integer getPayChannelId() {
		return payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.pay_channel_id
	 * @param payChannelId  the value for support_trade_types.pay_channel_id
	 * @mbggenerated
	 */
	public void setPayChannelId(Integer payChannelId) {
		this.payChannelId = payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.factory_id
	 * @return  the value of support_trade_types.factory_id
	 * @mbggenerated
	 */
	public Integer getFactoryId() {
		return factoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.factory_id
	 * @param factoryId  the value for support_trade_types.factory_id
	 * @mbggenerated
	 */
	public void setFactoryId(Integer factoryId) {
		this.factoryId = factoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.service_rate
	 * @return  the value of support_trade_types.service_rate
	 * @mbggenerated
	 */
	public Integer getServiceRate() {
		return serviceRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.service_rate
	 * @param serviceRate  the value for support_trade_types.service_rate
	 * @mbggenerated
	 */
	public void setServiceRate(Integer serviceRate) {
		this.serviceRate = serviceRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.service_profit
	 * @return  the value of support_trade_types.service_profit
	 * @mbggenerated
	 */
	public Integer getServiceProfit() {
		return serviceProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.service_profit
	 * @param serviceProfit  the value for support_trade_types.service_profit
	 * @mbggenerated
	 */
	public void setServiceProfit(Integer serviceProfit) {
		this.serviceProfit = serviceProfit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.trade_type_id
	 * @return  the value of support_trade_types.trade_type_id
	 * @mbggenerated
	 */
	public Integer getTradeTypeId() {
		return tradeTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.trade_type_id
	 * @param tradeTypeId  the value for support_trade_types.trade_type_id
	 * @mbggenerated
	 */
	public void setTradeTypeId(Integer tradeTypeId) {
		this.tradeTypeId = tradeTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.top_charge
	 * @return  the value of support_trade_types.top_charge
	 * @mbggenerated
	 */
	public Integer getTopCharge() {
		return topCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.top_charge
	 * @param topCharge  the value for support_trade_types.top_charge
	 * @mbggenerated
	 */
	public void setTopCharge(Integer topCharge) {
		this.topCharge = topCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.floor_charge
	 * @return  the value of support_trade_types.floor_charge
	 * @mbggenerated
	 */
	public Integer getFloorCharge() {
		return floorCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.floor_charge
	 * @param floorCharge  the value for support_trade_types.floor_charge
	 * @mbggenerated
	 */
	public void setFloorCharge(Integer floorCharge) {
		this.floorCharge = floorCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column support_trade_types.description
	 * @return  the value of support_trade_types.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column support_trade_types.description
	 * @param description  the value for support_trade_types.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}