package com.comdosoft.financial.user.domain.zhangfu;

public class SysConfig {

    /**
     * 积分兑换
     */
    public static final String PARAMNAME_INTEGRALCONVERT = "integralConvert";

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.id
     * 
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.param_name
     * 
     * @mbggenerated
     */
    private String paramName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.param_value
     * 
     * @mbggenerated
     */
    private String paramValue;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.remark
     * 
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.id
     * 
     * @return the value of sys_config.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.id
     * 
     * @param id
     *            the value for sys_config.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sys_config.param_name
     * 
     * @return the value of sys_config.param_name
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.param_name
     * 
     * @param paramName
     *            the value for sys_config.param_name
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * sys_config.param_value
     * 
     * @return the value of sys_config.param_value
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.param_value
     * 
     * @param paramValue
     *            the value for sys_config.param_value
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.remark
     * 
     * @return the value of sys_config.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.remark
     * 
     * @param remark
     *            the value for sys_config.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}