package com.comdosoft.financial.user.domain.zhangfu;

import java.util.Date;

public class SysMessage {

	private Integer id;
	private String title;
	private Date createdAt;
	private String content;
	
	 
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_messages.id
	 * @param id  the value for sys_messages.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_messages.title
	 * @return  the value of sys_messages.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_messages.title
	 * @param title  the value for sys_messages.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_messages.created_at
	 * @return  the value of sys_messages.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_messages.created_at
	 * @param createdAt  the value for sys_messages.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_messages.content
	 * @return  the value of sys_messages.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_messages.content
	 * @param content  the value for sys_messages.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content;
	}
}