package com.comdosoft.financial.user.domain.trades;

import java.util.Date;

public class GoodProfit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_profits.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_profits.profit
	 * @mbggenerated
	 */
	private Integer profit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_profits.types
	 * @mbggenerated
	 */
	private Byte types;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_profits.agent_id
	 * @mbggenerated
	 */
	private Integer agentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column good_profits.create_at
	 * @mbggenerated
	 */
	private Date createAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_profits.id
	 * @return  the value of good_profits.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_profits.id
	 * @param id  the value for good_profits.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_profits.profit
	 * @return  the value of good_profits.profit
	 * @mbggenerated
	 */
	public Integer getProfit() {
		return profit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_profits.profit
	 * @param profit  the value for good_profits.profit
	 * @mbggenerated
	 */
	public void setProfit(Integer profit) {
		this.profit = profit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_profits.types
	 * @return  the value of good_profits.types
	 * @mbggenerated
	 */
	public Byte getTypes() {
		return types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_profits.types
	 * @param types  the value for good_profits.types
	 * @mbggenerated
	 */
	public void setTypes(Byte types) {
		this.types = types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_profits.agent_id
	 * @return  the value of good_profits.agent_id
	 * @mbggenerated
	 */
	public Integer getAgentId() {
		return agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_profits.agent_id
	 * @param agentId  the value for good_profits.agent_id
	 * @mbggenerated
	 */
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column good_profits.create_at
	 * @return  the value of good_profits.create_at
	 * @mbggenerated
	 */
	public Date getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column good_profits.create_at
	 * @param createAt  the value for good_profits.create_at
	 * @mbggenerated
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}
}