package com.comdosoft.financial.user.domain.trades;

import java.util.Date;

public class TradeTotalRegionReport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_total_region_reports.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_total_region_reports.trade_time
	 * @mbggenerated
	 */
	private Date tradeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_total_region_reports.region_id
	 * @mbggenerated
	 */
	private Integer regionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_total_region_reports.trade_num
	 * @mbggenerated
	 */
	private Integer tradeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_total_region_reports.trade_sum
	 * @mbggenerated
	 */
	private Integer tradeSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_total_region_reports.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_total_region_reports.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_total_region_reports.id
	 * @return  the value of trade_total_region_reports.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_total_region_reports.id
	 * @param id  the value for trade_total_region_reports.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_total_region_reports.trade_time
	 * @return  the value of trade_total_region_reports.trade_time
	 * @mbggenerated
	 */
	public Date getTradeTime() {
		return tradeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_total_region_reports.trade_time
	 * @param tradeTime  the value for trade_total_region_reports.trade_time
	 * @mbggenerated
	 */
	public void setTradeTime(Date tradeTime) {
		this.tradeTime = tradeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_total_region_reports.region_id
	 * @return  the value of trade_total_region_reports.region_id
	 * @mbggenerated
	 */
	public Integer getRegionId() {
		return regionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_total_region_reports.region_id
	 * @param regionId  the value for trade_total_region_reports.region_id
	 * @mbggenerated
	 */
	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_total_region_reports.trade_num
	 * @return  the value of trade_total_region_reports.trade_num
	 * @mbggenerated
	 */
	public Integer getTradeNum() {
		return tradeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_total_region_reports.trade_num
	 * @param tradeNum  the value for trade_total_region_reports.trade_num
	 * @mbggenerated
	 */
	public void setTradeNum(Integer tradeNum) {
		this.tradeNum = tradeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_total_region_reports.trade_sum
	 * @return  the value of trade_total_region_reports.trade_sum
	 * @mbggenerated
	 */
	public Integer getTradeSum() {
		return tradeSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_total_region_reports.trade_sum
	 * @param tradeSum  the value for trade_total_region_reports.trade_sum
	 * @mbggenerated
	 */
	public void setTradeSum(Integer tradeSum) {
		this.tradeSum = tradeSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_total_region_reports.created_at
	 * @return  the value of trade_total_region_reports.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_total_region_reports.created_at
	 * @param createdAt  the value for trade_total_region_reports.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_total_region_reports.updated_at
	 * @return  the value of trade_total_region_reports.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_total_region_reports.updated_at
	 * @param updatedAt  the value for trade_total_region_reports.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}