package com.comdosoft.financial.user.domain.trades;

import java.util.Date;

public class TradeDayReport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.trade_date
	 * @mbggenerated
	 */
	private Date tradeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.trade_num
	 * @mbggenerated
	 */
	private Integer tradeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.trade_sum
	 * @mbggenerated
	 */
	private Integer tradeSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.order_num
	 * @mbggenerated
	 */
	private Integer orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.new_user_num
	 * @mbggenerated
	 */
	private Integer newUserNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.terminal_apply_num
	 * @mbggenerated
	 */
	private Integer terminalApplyNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_day_reports.created_at
	 * @mbggenerated
	 */
	private Date createdAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.id
	 * @return  the value of trade_day_reports.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.id
	 * @param id  the value for trade_day_reports.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.trade_date
	 * @return  the value of trade_day_reports.trade_date
	 * @mbggenerated
	 */
	public Date getTradeDate() {
		return tradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.trade_date
	 * @param tradeDate  the value for trade_day_reports.trade_date
	 * @mbggenerated
	 */
	public void setTradeDate(Date tradeDate) {
		this.tradeDate = tradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.trade_num
	 * @return  the value of trade_day_reports.trade_num
	 * @mbggenerated
	 */
	public Integer getTradeNum() {
		return tradeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.trade_num
	 * @param tradeNum  the value for trade_day_reports.trade_num
	 * @mbggenerated
	 */
	public void setTradeNum(Integer tradeNum) {
		this.tradeNum = tradeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.trade_sum
	 * @return  the value of trade_day_reports.trade_sum
	 * @mbggenerated
	 */
	public Integer getTradeSum() {
		return tradeSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.trade_sum
	 * @param tradeSum  the value for trade_day_reports.trade_sum
	 * @mbggenerated
	 */
	public void setTradeSum(Integer tradeSum) {
		this.tradeSum = tradeSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.order_num
	 * @return  the value of trade_day_reports.order_num
	 * @mbggenerated
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.order_num
	 * @param orderNum  the value for trade_day_reports.order_num
	 * @mbggenerated
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.new_user_num
	 * @return  the value of trade_day_reports.new_user_num
	 * @mbggenerated
	 */
	public Integer getNewUserNum() {
		return newUserNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.new_user_num
	 * @param newUserNum  the value for trade_day_reports.new_user_num
	 * @mbggenerated
	 */
	public void setNewUserNum(Integer newUserNum) {
		this.newUserNum = newUserNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.terminal_apply_num
	 * @return  the value of trade_day_reports.terminal_apply_num
	 * @mbggenerated
	 */
	public Integer getTerminalApplyNum() {
		return terminalApplyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.terminal_apply_num
	 * @param terminalApplyNum  the value for trade_day_reports.terminal_apply_num
	 * @mbggenerated
	 */
	public void setTerminalApplyNum(Integer terminalApplyNum) {
		this.terminalApplyNum = terminalApplyNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_day_reports.created_at
	 * @return  the value of trade_day_reports.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_day_reports.created_at
	 * @param createdAt  the value for trade_day_reports.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
}